exc_1 Done
devhadeelghourani/PythonOOPTask pull request #1
Opened 2022-03-14 08:30 UTC by devhadeelghourani

2022-03-14 14:39 UTC, belalali1998 requested changes

2022-03-14 14:39 UTC, belal-b-ali commented on exc_1.py
> +        print("Current Location: ", self.get_plam_location())
```suggestion
        print("Current Location: ", self.get_plane_location())
```

2022-03-14 14:39 UTC, belal-b-ali commented on exc_1.py
> +        print("Fuel: ", self.fuel())
`fuel` is attribute it's not callable

2022-03-14 14:39 UTC, belalali1998 commented on exc_1.py
> +        print(self.fly())
why you are printing `fly` !?

2022-03-14 14:39 UTC, belal-b-ali commented on exc_1.py
> +        self.min_fuel_needed = min_fuel
using `self` is not needed here

2022-03-14 15:04 UTC, devhadeelghourani commented on exc_1.py
> +        print("Current Location: ", self.get_plam_location())
Done..

2022-03-15 09:13 UTC, belalali1998 approved these changes

2022-03-15 09:15 UTC, merged